### ISSUE TITLE
v1.3.2 not released to Arduino?

### ISSUE THREAD

**Issue by friedl-priv** [mike-matera/FastPID#16] opened 2021-03-09 23:16 UTC
Hi!

Forgive my ignorance, but when I use the Arduino library manager (v1.8.13) I can only install FastPID up to v1.3.1. 

You released v1.3.2 back in 2019. 

How are your changes propagated to Arduino library manager?

**Comment by zaasman** [comment] 2021-05-12 19:09
It looks to me that the issue is simply the library.properties file was not updated with the new version, so the Arduino Library Manager does not recognize it as a new release.

You can simply download, or clone, the package from here and manually replace the files in your library folder (found in your sketchbook folder). The Library Manager will still recognize it as v1.3.1, but you'll in fact have the latest files.

**Comment by friedl-priv** [comment] 2021-05-18 20:28
Might I just suggest to bump the version to v1.3.3, correct the library.properties and then do a release?

**Comment by mike-matera** [comment] 2023-04-18 20:53
Fixed by #19 . Thanks!

**Closed by mike-matera** 2023-04-18 20:53 UTC
